'use strict';

var React = require('react/addons');

var Icon = require('../../../icons');

// Export React so the devtools can find it
(window !== window.top ? window.top : window).React = React;

// CSS
require('../../styles/normalize.css');
require('../../styles/main.css');


var App = React.createClass({
  render: function() {
    return (
      <div className="main">
        <Icon.Add />
        <Icon.AddressBook />
        <Icon.AddressBook2 />
        <Icon.AlignBottom />
        <Icon.AlignHorizontalCenters />
        <Icon.AlignLeftEdges />
        <Icon.AlignRightActions />
        <Icon.AlignTop />
        <Icon.AlignVerticalCenters />
        <Icon.Anchor />
        <Icon.ArrowDown />
        <Icon.ArrowLeft />
        <Icon.ArrowRight />
        <Icon.ArrowUp />
        <Icon.Asterisk />
        <Icon.Attachment />
        <Icon.Attachment2 />
        <Icon.AudioHigh />
        <Icon.AudioMid />
        <Icon.AudioMute />
        <Icon.AudoLow />
        <Icon.Batter1002 />
        <Icon.Batter20 />
        <Icon.Batter60 />
        <Icon.Batter602 />
        <Icon.Battery100 />
        <Icon.Battery202 />
        <Icon.Battery40 />
        <Icon.Battery402 />
        <Icon.Battery80 />
        <Icon.Battery802 />
        <Icon.BatteryCharge />
        <Icon.BatteryCharge2 />
        <Icon.BatteryEmpty />
        <Icon.BatteryEmpty2 />
        <Icon.Bell />
        <Icon.Bell2 />
        <Icon.BellMute />
        <Icon.BellMute2 />
        <Icon.Bin />
        <Icon.Bin2 />
        <Icon.Book />
        <Icon.Book2 />
        <Icon.BookLines />
        <Icon.BookLines2 />
        <Icon.BrightnessHigh />
        <Icon.BrightnessLow />
        <Icon.Browser />
        <Icon.Browser2 />
        <Icon.BrowserClose />
        <Icon.BrowserClose2 />
        <Icon.BrowserDownload />
        <Icon.BrowserDownload2 />
        <Icon.BrowserMinimize />
        <Icon.BrowserMinimize2 />
        <Icon.BrowserNewWindow />
        <Icon.BrowserNewWindow2 />
        <Icon.BrowserUpload />
        <Icon.BrowserUpload2 />
        <Icon.BrowserWindows />
        <Icon.BrowserWindows2 />
        <Icon.Bulb />
        <Icon.Bulb2 />
        <Icon.Bullet />
        <Icon.Bullhorn />
        <Icon.Bullhorn2 />
        <Icon.Calendar />
        <Icon.Camera />
        <Icon.Camera2 />
        <Icon.Camera3 />
        <Icon.Cassette />
        <Icon.Clipboard />
        <Icon.Clipboard2 />
        <Icon.Clock />
        <Icon.Cloud />
        <Icon.CloudAdd />
        <Icon.CloudAdd2 />
        <Icon.CloudDownload />
        <Icon.CloudRemove />
        <Icon.CloudRemove2 />
        <Icon.CloudUpload />
        <Icon.Cmd />
        <Icon.Code />
        <Icon.Compass />
        <Icon.Compose />
        <Icon.Compose2 />
        <Icon.Compose3 />
        <Icon.Compose4 />
        <Icon.Contract />
        <Icon.Contract2 />
        <Icon.Contract3 />
        <Icon.Contrast />
        <Icon.Converge />
        <Icon.Crate />
        <Icon.CreditCard />
        <Icon.CreditCard2 />
        <Icon.CreditCard3 />
        <Icon.CreditCard4 />
        <Icon.Crop />
        <Icon.CurlyBrace />
        <Icon.CurlyBrace2 />
        <Icon.Database />
        <Icon.DatabaseAdd />
        <Icon.DatabaseRemove />
        <Icon.Delete />
        <Icon.DistributeBottomEdges />
        <Icon.DistributeHorizontalCenters />
        <Icon.DistributeLeftEdges />
        <Icon.DistributeRightEdges />
        <Icon.DistributeTopEdges />
        <Icon.DistributeVerticalCenters />
        <Icon.Document />
        <Icon.DocumentAdd />
        <Icon.DocumentRemove />
        <Icon.Droplet />
        <Icon.Ellipsis />
        <Icon.Exclude />
        <Icon.Expand />
        <Icon.Expand2 />
        <Icon.Expand3 />
        <Icon.Eye />
        <Icon.Eye2 />
        <Icon.FlaskEmpty />
        <Icon.FlaskFull />
        <Icon.Floppy />
        <Icon.Flux />
        <Icon.Folder />
        <Icon.Folder2 />
        <Icon.FolderAdd />
        <Icon.FolderAdd2 />
        <Icon.FolderDuplicate />
        <Icon.FolderDuplicate2 />
        <Icon.FolderRemove />
        <Icon.FolderRemove2 />
        <Icon.Grid />
        <Icon.Grid2 />
        <Icon.Headphones />
        <Icon.HeartEmpty />
        <Icon.HeartFull />
        <Icon.HeartHalf />
        <Icon.Image />
        <Icon.In />
        <Icon.Inbox />
        <Icon.Inbox2 />
        <Icon.Inifinity />
        <Icon.Intersect />
        <Icon.Key />
        <Icon.Key2 />
        <Icon.Keys />
        <Icon.LayoutColumnCenter />
        <Icon.LayoutContentLeft />
        <Icon.LayoutContentLeft2 />
        <Icon.LayoutContentRight />
        <Icon.LayoutContentRight2 />
        <Icon.LayoutSidebarLeft />
        <Icon.LayoutSidebarRight />
        <Icon.Link />
        <Icon.Link2 />
        <Icon.List />
        <Icon.List2 />
        <Icon.Locked />
        <Icon.Mail />
        <Icon.Mail2 />
        <Icon.Mail3 />
        <Icon.Map />
        <Icon.Map2 />
        <Icon.Marquee />
        <Icon.MarqueeDownload />
        <Icon.MarqueeMinus />
        <Icon.MarqueePlus />
        <Icon.MarqueeUpload />
        <Icon.Maximise />
        <Icon.Menu />
        <Icon.Menu2 />
        <Icon.MenuPullDown />
        <Icon.MenuPullUp />
        <Icon.Microphone />
        <Icon.Microphone2 />
        <Icon.Minus />
        <Icon.Mixer />
        <Icon.Newspaper />
        <Icon.Newspaper2 />
        <Icon.Nib />
        <Icon.Nope />
        <Icon.Notes />
        <Icon.Out />
        <Icon.Outbox />
        <Icon.Outbox2 />
        <Icon.Outgoing />
        <Icon.PaperRipped />
        <Icon.PaperRoll />
        <Icon.PaperRollRipped />
        <Icon.ParagraphCenter />
        <Icon.ParagraphCenter2 />
        <Icon.ParagraphJustify />
        <Icon.ParagraphJustify2 />
        <Icon.ParagraphLeft />
        <Icon.ParagraphLeft2 />
        <Icon.ParagraphRight />
        <Icon.ParagraphRight2 />
        <Icon.Pen />
        <Icon.Pencil />
        <Icon.Pin />
        <Icon.Pin2 />
        <Icon.Plus />
        <Icon.Podcast />
        <Icon.Podcast2 />
        <Icon.Polaroid />
        <Icon.Polaroid2 />
        <Icon.Power />
        <Icon.Print />
        <Icon.Quill />
        <Icon.Quill2 />
        <Icon.Refresh />
        <Icon.Reminder />
        <Icon.Remove />
        <Icon.Repeat />
        <Icon.Repeat2 />
        <Icon.Return />
        <Icon.Rulers />
        <Icon.Safe />
        <Icon.Search />
        <Icon.Search2 />
        <Icon.Section />
        <Icon.Settings />
        <Icon.Settings2 />
        <Icon.Settings3 />
        <Icon.Shred />
        <Icon.Shuffle />
        <Icon.Sleep />
        <Icon.SpeechBubbleCenter />
        <Icon.SpeechBubbleCenter2 />
        <Icon.SpeechBubbleCenter3 />
        <Icon.SpeechBubbleLef3 />
        <Icon.SpeechBubbleLeft />
        <Icon.SpeechBubbleLeft2 />
        <Icon.SpeechBubbleLeft4 />
        <Icon.SpeechBubbleRight />
        <Icon.SpeechBubbleRight2 />
        <Icon.SpeechBubbleRight3 />
        <Icon.SpeechBubbleRight4 />
        <Icon.Spiiner3 />
        <Icon.Spinner />
        <Icon.Spinner2 />
        <Icon.Split />
        <Icon.Split2 />
        <Icon.Spool />
        <Icon.SquareBrackets />
        <Icon.Stamp />
        <Icon.Stamp2 />
        <Icon.Stiffy />
        <Icon.Store />
        <Icon.Store2 />
        <Icon.Subtract />
        <Icon.Support />
        <Icon.Support2 />
        <Icon.Support3 />
        <Icon.Swap />
        <Icon.Swap2 />
        <Icon.Swatch />
        <Icon.Swatches />
        <Icon.SwitchOff />
        <Icon.SwitchOn />
        <Icon.Tag />
        <Icon.Tag2 />
        <Icon.Tag3 />
        <Icon.Tag4 />
        <Icon.Terminal />
        <Icon.Terminal2 />
        <Icon.Terminal3 />
        <Icon.Tilde />
        <Icon.Timeline />
        <Icon.ToggleOff />
        <Icon.ToggleOn />
        <Icon.Transfer />
        <Icon.Tray />
        <Icon.Unite />
        <Icon.Unlocked />
        <Icon.User />
        <Icon.User2 />
        <Icon.User3 />
        <Icon.UserCard />
        <Icon.Users />
        <Icon.Video />
        <Icon.Video2 />
        <Icon.Vinyl />
        <Icon.Voicemail />
        <Icon.Wallet />
        <Icon.Wallet2 />
        <Icon.Wave />
        <Icon.Wave2 />
        <Icon.WifiHigh/>
        <Icon.WifiLow />
        <Icon.WifiMid />
        <Icon.Wiggle />
        <Icon.Windows />
        <Icon.ZoomIn />
        <Icon.ZoomIn2 />
        <Icon.ZoomOut />
        <Icon.ZoomOut2 />
      </div>
    );
  }
});
React.render(<App />, document.getElementById('content'));

module.exports = App;
